server:
  port: 9966
  servlet:
    context-path: /api
spring:
  application:
    name: rocket-pt
  profiles:
    active: dev
  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: ss@qq.com
    password: yxwrnwnxvtssdagd
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
  datasource:
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      #最小允许值为30000ms（30秒）。 默认值：1800000（30分钟）
      max-lifetime: 60000
      #允许池达到的最大大小，包括空闲和使用中的连接。
      #此值将确定到数据库后端的最大实际连接数。合理的值最好由您的执行环境确定。 默认值：10
      maximum-pool-size: 500
      minimum-idle: 10
      read-only: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    local-cache-scope: statement
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true

logging:
  file:
    path: logs

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rocketpt.server

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
