spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rocketpt.plexpt.com:33061/rocketdev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: rocketpt


  mail:
    host: smtp.qq.com
    username: ss@qq.com
    password: yxwrnwnxvtssdagd
  data:
    redis:
#      host: rocketpt.plexpt.com
#      port: 6377
#      password: pt
#      database: 0
      url: redis://pt@rocketpt.plexpt.com:6379/0
