spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://txcd.plexpt.com:3306/rocket?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: rocket
    password: xp8bEGccaAG6a8pd
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always
#      continue-on-error: true


  mail:
    host: smtp.qq.com
    username: ss@qq.com
    password: yxwrnwnxvtssdagd
